services:

#  nutriscan:
#      container_name: nutriscan
#      build:
#        context: .
#        dockerfile: Dockerfile
#      ports:
#        - "8080:8080"
#      environment:
#        DB_URL: jdbc:postgresql://postgres-app:5432/${APP_DB_NAME:-nutri_scan}
#        DB_USERNAME: ${APP_DB_USER:-admin}
#        DB_PASSWORD: ${APP_DB_PASSWORD:-admin}
#      depends_on:
#        postgres-app:
#          condition: service_healthy
#        keycloak:
#          condition: service_started

  postgres-app:
    container_name: postgres-app
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${APP_DB_NAME:-nutri_scan}
      POSTGRES_USER: ${APP_DB_USER:-admin}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD:-admin}
    volumes:
      - app-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d nutri_scan -U admin"]
      interval: 5s
      retries: 10

  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${KC_DB_NAME:-keycloak}
      POSTGRES_USER: ${KC_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD:-1234}
    volumes:
      - kc-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      retries: 10

  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: keycloak/Dockerfile
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/${KC_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KC_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-1234}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-admin}
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    volumes:
      - ./keycloak/themes/nutriscan:/opt/keycloak/themes/nutriscan

    ports:
      - "8081:8080"
      - "9000:9000"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/health/ready" ]
#      interval: 10s
#      retries: 10

volumes:
  kc-pgdata:
  app-pgdata:
