# Internal docker network address Spring actually uses to fetch signing keys
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://auth.nutriscan.dev/realms/nutriscan/protocol/openid-connect/certs

keycloak.server.url=https://auth.nutriscan.dev

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.nutriscan.dev/realms/nutriscan

spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}

spring.elasticsearch.uris=${ELASTICSEARCH_URI}
spring.elasticsearch.username=${ELASTICSEARCH_USERNAME}
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD}

spring.rabbitmq.host=${RABBITMQ_HOST}