# Internal docker network address Spring actually uses to fetch signing keys
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/nutriscan/protocol/openid-connect/certs

keycloak.server.url=http://keycloak:8080

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.url=redis://redis:6379

spring.elasticsearch.uris=http://elasticsearch:9200
spring.rabbitmq.host=rabbitmq