spring.application.name=NutriScan
spring.main.banner-mode=off

# so the path comes out as https instead of http
server.forward-headers-strategy=native

server.port=8080
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite

spring.ai.openai.api-key= ${OPENCODE_API_KEY}
spring.ai.openai.base-url= https://opencode.ai/zen/v1
spring.ai.openai.chat.model=deepseek-v4-flash-free
  #nemotron-3-ultra-free
logging.level.org.springframework.ai=TRACE
logging.level.com.openai=TRACE
logging.level.org.springframework.web.client=TRACE

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/nutriscan

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}
keycloak.admin.client-id=admin-cli
keycloak.server.url=http://localhost:8081
keycloak.realm.name=nutriscan

spring.cache.type=redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

tavily.url=https://api.tavily.com/search
tavily.api-key=${TAVILY_API_KEY}

bedrock.base-url=http://apiaccess.iti.net.eg/api/v1
bedrock.api-key=${BEDROCK_API_KEY}
#bedrock.model-id=anthropic.claude-sonnet-4-6

# account config
nutriscan.account.deletion-grace-period-days=15