# Internal docker network address Spring actually uses to fetch signing keys
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://nutriscan-ai-keycloak-production-fd80.up.railway.app/realms/nutriscan/protocol/openid-connect/certs

keycloak.server.url=https://nutriscan-ai-keycloak-production-fd80.up.railway.app

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://nutriscan-ai-keycloak-production-fd80.up.railway.app/realms/nutriscan