spring.application.name=NutriScan
spring.main.banner-mode=off

server.port=8080
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/nutriscan

spring.application.security.oauth2.expiration-time=86400000
spring.application.security.oauth2.refresh-token.expiration=604800000

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}
keycloak.admin.client-id=admin-cli
keycloak.server.url=http://localhost:8081
keycloak.realm.name=nutriscan

spring.cache.type=redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}