INSERT INTO allergies (name) VALUES
('Peanuts'),
('Tree Nuts'),
('Milk'),
('Eggs'),
('Soy'),
('Wheat'),
('Fish'),
('Shellfish'),
('Sesame'),
('Pollen'),
('Dust Mites'),
('Mold'),
('Pet Dander'),
('Latex'),
('Penicillin'),
('Bee Stings'),
('Nickel'),
('Sunlight'),
('Perfume'),
('Insect Bites')
ON CONFLICT (name) DO NOTHING;

INSERT INTO diseases (name) VALUES
('Diabetes'),
('Hypertension'),
('Asthma'),
('Chronic Kidney Disease'),
('Coronary Artery Disease'),
('Heart Failure'),
('Chronic Obstructive Pulmonary Disease'),
('Tuberculosis'),
('Pneumonia'),
('Influenza'),
('COVID-19'),
('Hepatitis B'),
('Hepatitis C'),
('HIV/AIDS'),
('Malaria'),
('Dengue Fever'),
('Migraine'),
('Epilepsy'),
('Hypothyroidism'),
('Hyperthyroidism'),
('Osteoarthritis'),
('Rheumatoid Arthritis'),
('Osteoporosis'),
('Anemia'),
('Depression'),
('Anxiety Disorder'),
('Parkinson''s Disease'),
('Alzheimer''s Disease'),
('Cancer'),
('Obesity')
ON CONFLICT (name) DO NOTHING;